### ISSUE TITLE
Support non-failing action

### ISSUE THREAD

**Issue by jusdino** [zaproxy/action-af#12]
Looking at the [ZAP documentation about exit status](https://www.zaproxy.org/docs/automate/automation-framework/#exit-value), it appears that the application does not support customizing exit status, so we have to specifically suppress the exit status with something like `|| [ $? -ne 1 ]`. Obviously, we can't do that when running ZAP via a GitHub Action. Can you add some option to suppress that exit status in the Action so that we can generate a ZAP scan report that is for manual review without worrying about alerts throwing a big ❌ on our pull requests?

**Comment by psiinon** [comment]
Makes sense. We could add an option in the automation framework so that it can be used in other places as well.

**Comment by thc202** [comment]
Closing with zaproxy/zaproxy#6928 (solution of the previous comment).
